FROM ubuntu

#update, install curl, zip/unzip
RUN apt-get update -y \
    && apt-get install curl -y \
    && apt-get install zip unzip

#install python and bot03
RUN && apt-get install python3-pip -y \
    && pip install boto3

