version: '3'

services:
  py_env_1:
    build: 
      context: .
      dockerfile: Dockerfile
    image: ubuntu_py_aws
    environment:
      ENVIRONMENT: dev
    volumes:
      - ./Lambda_EC2:/Scripts

  py_env_2:
    build: 
      context: .
      dockerfile: Dockerfile
    image: ubuntu_py_aws
    environment:
      ENVIRONMENT: prod

  py_env_3:
    build: 
      context: .
      dockerfile: Dockerfile
    image: ubuntu_py_aws
    environment:
      ENVIRONMENT: prod

      


